/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testDB;

import java.sql.*;

public class App {

    public static void main( String[] args ) throws SQLException {
        //create connection for a server installed in localhost, with a user "root" with no password
        try (Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost/ok", "root", "go")) {
            // create a Statement
            try (Statement stmt = conn.createStatement()) {
                //execute query
                try (ResultSet rs = stmt.executeQuery("SELECT * from user")) {
                    //position result to firsts
                    rs.first();
                    System.out.println(rs.getString("id")); //result is "Hello World!"
                }
            }
        }
    }
}