/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package speda;

import org.junit.Test;
import static org.junit.Assert.*;

public class MountainBikeTest {
    @Test
    public void multiplicationOfZeroIntegersShouldReturnZero() {
        MountainBike ontel = new MountainBike(1,1,1,1);
           // assert statements
        assertEquals(1,ontel.getGear());
        assertEquals(1,ontel.getCadence());
        assertEquals(1,ontel.getSpeed());

     
    
    }
}
