/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inittesting;

public class kalkulator {
    public String gethalo() {
        return "kalkulator1";
    }

    public String ok1() {
     String b ="ceksound kalkulator";
     

        return b;
    }

    
 public int hitung1(int a, int b){
    int nilai = 0;
       return nilai = a*b;
    }

  public int multiply(int a, int b){
    int nilai = 0;
    return nilai = a*b;
    
     }
  



    


}
