/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package speda;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        MountainBike ontel = new MountainBike(1,1,1,1);
        System.out.println(ontel.getGear());
        System.out.println(ontel.getCadence());
        System.out.println(ontel.getSpeed());
    }
}
