/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inittesting;

import org.junit.Test;
import static org.junit.Assert.*;

public class kalkulatorTest {
    @Test public void testkalkulatorHasAGreeting() {
        kalkulator classUnderTest = new kalkulator();
        assertNotNull("app should have a greeting", classUnderTest.gethalo());
       
    } 

    @Test public void testkalkulatorHasAhitung1() {
        kalkulator classUnderTest = new kalkulator();
       
       assertEquals(9,classUnderTest.hitung1(3,3));
    } 

  @Test
    public void multiplicationOfZeroIntegersShouldReturnZero() {
        kalkulator classUnderTest = new kalkulator();

        // assert statements
      assertEquals(0, classUnderTest.multiply(10, 0));
        assertEquals(0, classUnderTest.multiply(0, 10));
        assertEquals(0, classUnderTest.multiply(0, 0));
    }
    
}


