/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cfdo;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws InterruptedException {
        System.out.println(new App().getGreeting());

        //deadlook
        Thread myThread1 = new Thread(new Deadlock(), "thread-1");
        Thread myThread2 = new Thread(new Deadlock(), "thread-2");
        myThread1.start();
        myThread2.start();

        //ConsumerProduser

     //   ConsumerProducer custom = new ConsumerProducer();
      // custom.run();
       

    }
}
